### ISSUE TITLE
Bug: Unable to update staff information

### ISSUE THREAD

**Issue by peppapighs** [ShenyiCui/Lions-Rails-6-IssueTicketing#12]
## Issue Description (Unexpected Behaviour)
- NoMethodError when updating staff information

## Expected Behaviour
- Should update staff information without error

## Steps to Reproduce the Error
1. Go to Administration > Staff
2. Click on Pencil icon button on any staff to edit staff information
3. Scroll down to the bottom and click 'Update Staff' button

## Screenshots / Others (Additional context)
![image](https://user-images.githubusercontent.com/41262596/173550052-1327f492-57ed-4175-9cff-051a897d0884.png)

**Comment by ekowidianto** [comment]
https://rubyinrails.com/2019/04/09/rails-6-1-activerecord-deprecates-update-attributes-methods/

This was not caught probably because we are adding cvwo_ prefix (note that cvwo_ prefix is added for cvwo_audit purpose - so that the action is logged)

@ShenyiCui @Santosh3007 
Can we go through all the removals section again? thanks

**Comment by ekowidianto** [comment]
Solution: change to `update`

**Comment by ShenyiCui** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/merge_requests/2597/diffs?commit_id=ca3e1d24392883102e57bbe07e776b2856fe9301
