### ISSUE TITLE
Bug: Missing zone codes in volunteer listing table

### ISSUE THREAD

**Issue by jasonqiu212** [ShenyiCui/Lions-Rails-6-IssueTicketing#4]
## Issue Description (Unexpected Behaviour)
- Zone codes are missing in 'Volunteer Listing' table for rejected volunteers.

## Expected Behaviour
- The zone codes should show up for the volunteers, as per staging site and `master` branch.

## Steps to Reproduce the Error
1. Go to 'New Volunteers' and go to the 'Volunteer Listing' section.
2. Apply the 'Rejected' filter.
3. The zone codes do not show up.

## Screenshots / Others (Additional context)
Localhost:
![Screen Shot 2022-06-14 at 3 26 13 PM](https://user-images.githubusercontent.com/25262042/173518809-4cf03c9b-7461-4a40-b170-b807a150b645.png)

Staging:
![Screen Shot 2022-06-14 at 3 26 17 PM](https://user-images.githubusercontent.com/25262042/173518824-3f2078b9-3ebc-4221-924b-7e56869d2183.png)

**Comment by ekowidianto** [comment]
The `active_people_region_profiles` retrieves the zone codes for only active prp, since these prps are inactive, region_ids is empty.. probably need to use `people_region_profiles` rather than `active_people_region_profiles` for the case of "rejected" volunteer/befriendeer

![image](https://user-images.githubusercontent.com/42570513/173587352-805d6408-b384-44fd-9615-e11ed0127589.png)

**Comment by ekowidianto** [comment]
Seems like the zone codes only appear in staging.. if we use the master branch, the zone codes also do not appear

**Comment by Santosh3007** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/b0a092e980213c9a852faa14843ee6829d58caff
