### ISSUE TITLE
Bug: Mismatch dates for HPC Monthly Summary Report To Finance

### ISSUE THREAD

**Issue by peppapighs** [ShenyiCui/Lions-Rails-6-IssueTicketing#7]
## Issue Description (Unexpected Behaviour)
- The value date, deposite date, and receipt date in the report table is one day earlier than it should have been
- This mismatch happens in generated excel file as well

## Expected Behaviour
- The dates should be the same and not one day earlier in both the view and the excel file

## Steps to Reproduce the Error
1. Go to Reports > HPC > Monthly Summary Report To Finance
2. See the mismatch in 'Value Date', 'Deposit Date', and 'Receipt Date' columns

## Screenshots / Others (Additional context)
localhost
![image](https://user-images.githubusercontent.com/41262596/173529372-428f9372-76be-4a96-8b24-f5e94e502f79.png)

![image](https://user-images.githubusercontent.com/41262596/173530024-b0290556-279e-4483-ae83-cf8ab0f3951b.png)

Staging
![image](https://user-images.githubusercontent.com/41262596/173529494-3dfb6d49-443f-4d88-8114-22a062c2803a.png)

![image](https://user-images.githubusercontent.com/41262596/173530100-45ff6b3c-fa30-4ac8-a421-abcca77e05f6.png)

The dates are correct in HPC > Bank Deposits > View Bank Deposit

**Comment by ekowidianto** [comment]
Check UTC

**Comment by ShenyiCui** [comment]
Identified Possible Errors of UTC conversion:
`app/models/reports/volunteer_course_attendance_report.rb:198`
`app/controllers/reports/hpc_monthly_void_report_controller.rb:33`
`app/controllers/reports/hpc_monthly_finance_summary_report_controller.rb:30`
`app/controllers/reports/hpc_monthly_finance_summary_report_controller.rb:37`
`app/controllers/reports/hpc_monthly_finance_summary_report_controller.rb:51`

The lines stated above need to have their UTC postfix removed in order to match Master. However, we are currently in the process of checking the DB to see whether Master is really correct.

**Comment by ekowidianto** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/merge_requests/2582/diffs?commit_id=e38757c7968676c271e93f5a9e52b239d4ddbbe0
